### ISSUE TITLE
Upgrades not Working

### ISSUE THREAD

**Issue by hueychen27** [hueychen27/Popcorn_Clicker#2]
In the upgrades code in [main.js](https://github.com/hueychen27/Popcorn_Clicker/blob/main/main.js) line 65 to line 149. The upgrades and not the buildings are not showing on the screen. Checking the console returns no error as an error would break the game. Fixing this would be splendid.

**Comment by PANDASARECOOOL** [comment]
I think the reason why is that when you got the image files in the JS object "image" you didn't use the correct file path, and when getting the images I think you have to use something like "img/imagename.svg" or something like that. If you use the wrong file path then the images dont show

**Comment by hueychen27** [comment]
The img tag is not even showing though. :/

**Comment by hueychen27** [comment]
@PANDASARECOOOL I have confirmed the source is correct.

**Comment by hueychen27** [comment]
@PANDASARECOOOL FIXED ISSUE
